{% set name = "ambiance" %}
{% set version = "1.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9f5a37efc20c7473c315f1f8ae791a685a9cc51ca83f295619b4c855d10b412c

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
  run:
    - python >=3.6
    - numpy
    - scipy

test:
  imports:
    - ambiance

about:
  home: https://github.com/airinnova/ambiance
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: A full implementation of the ICAO standard atmosphere 1993
  description: |
    Ambiance is a full implementation of the ICAO standard atmosphere 1993 written in Python.
    Based on International Civil Aviation Organization ; Manual Of The ICAO Standard Atmosphere
    -- 3rd Edition 1993 (Doc 7488) -- extended to 80 kilometres (262 500 feet).
  doc_url: https://ambiance.readthedocs.io/
  dev_url: https://github.com/airinnova/ambiance

extra:
  recipe-maintainers:
    - bryanwweber
